// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPKuzkADZOEAfKid5ei4xa-ONer9aYloM',
    appId: '1:996393076393:web:c316de39668ba75a298bb8',
    messagingSenderId: '996393076393',
    projectId: 'kemacetan-e8a3c',
    authDomain: 'kemacetan-e8a3c.firebaseapp.com',
    databaseURL: 'https://kemacetan-e8a3c-default-rtdb.firebaseio.com',
    storageBucket: 'kemacetan-e8a3c.firebasestorage.app',
    measurementId: 'G-1GXZ2TF3V3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcQiqj0pmSNoCJQA94v0P08hK5elySFi8',
    appId: '1:996393076393:android:1b781a0f3cbd228b298bb8',
    messagingSenderId: '996393076393',
    projectId: 'kemacetan-e8a3c',
    databaseURL: 'https://kemacetan-e8a3c-default-rtdb.firebaseio.com',
    storageBucket: 'kemacetan-e8a3c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPKuzkADZOEAfKid5ei4xa-ONer9aYloM',
    appId: '1:996393076393:web:972f1a457aab2789298bb8',
    messagingSenderId: '996393076393',
    projectId: 'kemacetan-e8a3c',
    authDomain: 'kemacetan-e8a3c.firebaseapp.com',
    databaseURL: 'https://kemacetan-e8a3c-default-rtdb.firebaseio.com',
    storageBucket: 'kemacetan-e8a3c.firebasestorage.app',
    measurementId: 'G-PWZT7YL1ZL',
  );
}
